version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/hello-flask
    environment:
      - FLASK_ENV=development
  redis:
    image: redis:bullseye
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
    entrypoint: rq worker --url=redis://redis:6379
    depends_on:
      - redis
      - web
